# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cooperative 0.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "cooperative"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Karen Lundgren"]
  s.date = "2014-05-08"
  s.description = "Cooperative provides Social Networking abilities to Rails 4 apps."
  s.email = "webmaster@sourcherryweb.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".idea/.generators",
    ".idea/.name",
    ".idea/.rakeTasks",
    ".idea/encodings.xml",
    ".idea/misc.xml",
    ".idea/modules.xml",
    ".idea/scopes/scope_settings.xml",
    ".idea/vcs.xml",
    ".idea/workspace.xml",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/cooperative/large/missing.png",
    "app/assets/images/cooperative/medium/missing.png",
    "app/assets/images/cooperative/thumb/missing.png",
    "app/assets/javascripts/cooperative.js",
    "app/assets/javascripts/follows.js",
    "app/assets/javascripts/forms.js",
    "app/assets/javascripts/modal.js",
    "app/assets/javascripts/statuses.js",
    "app/assets/javascripts/triggers.js",
    "app/assets/stylesheets/activities.css.scss",
    "app/assets/stylesheets/comments.css.scss",
    "app/assets/stylesheets/cooperative.css.scss",
    "app/assets/stylesheets/forms.css.scss",
    "app/assets/stylesheets/messages.css.scss",
    "app/assets/stylesheets/people.css.scss",
    "app/assets/stylesheets/ratings.css.scss",
    "app/assets/stylesheets/spinner.css.scss",
    "app/assets/stylesheets/tabs.css.scss",
    "app/assets/stylesheets/tags.css.scss",
    "app/controllers/activities_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/comments_controller.rb",
    "app/controllers/cooperative_controller.rb",
    "app/controllers/follows_controller.rb",
    "app/controllers/groups_controller.rb",
    "app/controllers/messages_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/people_controller.rb",
    "app/controllers/profile_controller.rb",
    "app/controllers/ratings_controller.rb",
    "app/controllers/statuses_controller.rb",
    "app/controllers/tags_controller.rb",
    "app/helpers/cooperative_helper.rb",
    "app/helpers/follows_helper.rb",
    "app/helpers/messages_helper.rb",
    "app/helpers/pages_helper.rb",
    "app/helpers/people_helper.rb",
    "app/helpers/ratings_helper.rb",
    "app/helpers/statuses_helper.rb",
    "app/helpers/tags_helper.rb",
    "app/mailers/.gitkeep",
    "app/models/ability.rb",
    "app/models/comment.rb",
    "app/models/follow.rb",
    "app/models/group.rb",
    "app/models/message.rb",
    "app/models/page.rb",
    "app/models/role.rb",
    "app/models/status.rb",
    "app/models/tag.rb",
    "app/models/user.rb",
    "app/views/activities/_activity.haml",
    "app/views/activities/_menu_item.html.haml",
    "app/views/activities/index.html.haml",
    "app/views/comments/_comment.html.haml",
    "app/views/comments/_comments.html.haml",
    "app/views/comments/_form.html.haml",
    "app/views/comments/create.js.erb",
    "app/views/comments/destroy.js.erb",
    "app/views/comments/index.html.haml",
    "app/views/comments/new.html.haml",
    "app/views/comments/show.html.haml",
    "app/views/follows/_auto_complete.html.haml",
    "app/views/follows/_person.html.haml",
    "app/views/follows/create.js.erb",
    "app/views/follows/destroy.js.erb",
    "app/views/follows/followers.html.haml",
    "app/views/follows/index.html.haml",
    "app/views/groups/_form.html.haml",
    "app/views/groups/_join_button.html.haml",
    "app/views/groups/_menu_item.html.haml",
    "app/views/groups/edit.html.haml",
    "app/views/groups/index.html.haml",
    "app/views/groups/join.js.erb",
    "app/views/groups/leave.js.erb",
    "app/views/groups/new.html.haml",
    "app/views/groups/show.html.haml",
    "app/views/layouts/422.html.haml",
    "app/views/layouts/422.js.erb",
    "app/views/layouts/_actionable_descriptor.html.haml",
    "app/views/layouts/_tinymce_init.html.haml",
    "app/views/layouts/_video.html.haml",
    "app/views/layouts/cooperative.html.haml",
    "app/views/layouts/partial.html.haml",
    "app/views/messages/_form_for_activities.html.haml",
    "app/views/messages/_menu_item.html.haml",
    "app/views/messages/_message.html.haml",
    "app/views/messages/_messages_table.html.haml",
    "app/views/messages/_submenu.html.haml",
    "app/views/messages/index.html.haml",
    "app/views/messages/new.html.haml",
    "app/views/messages/reply.html.haml",
    "app/views/messages/sent.html.haml",
    "app/views/messages/show.html.haml",
    "app/views/messages/trash.html.haml",
    "app/views/pages/_form.html.haml",
    "app/views/pages/_menu_items.html.haml",
    "app/views/pages/_page.html.haml",
    "app/views/pages/_submenu_for_person.html.haml",
    "app/views/pages/_widget.html.haml",
    "app/views/pages/activities/_created.html.haml",
    "app/views/pages/edit.html.haml",
    "app/views/pages/index.html.haml",
    "app/views/pages/new.html.haml",
    "app/views/pages/show.html.haml",
    "app/views/people/_auto_complete.html.haml",
    "app/views/people/_menu_item.html.haml",
    "app/views/people/_submenu.html.haml",
    "app/views/people/index.html.haml",
    "app/views/people/show.html.haml",
    "app/views/profile/edit.html.haml",
    "app/views/ratings/_info.html.haml",
    "app/views/ratings/_toggle.html.haml",
    "app/views/ratings/_total.html.haml",
    "app/views/ratings/_vote.html.haml",
    "app/views/ratings/rate.js",
    "app/views/statuses/_form.html.haml",
    "app/views/statuses/_form_for_activities.html.haml",
    "app/views/statuses/_form_for_sharing.html.haml",
    "app/views/statuses/_grab.html.haml",
    "app/views/statuses/_shareable.html.haml",
    "app/views/statuses/_status.html.haml",
    "app/views/statuses/activities/_created.html.haml",
    "app/views/statuses/activities/_mentioned_in.html.haml",
    "app/views/statuses/create.js.erb",
    "app/views/statuses/destroy.js.erb",
    "app/views/statuses/grab.js.erb",
    "app/views/statuses/new.html.haml",
    "app/views/statuses/show.html.haml",
    "app/views/tags/_auto_complete.html.haml",
    "app/views/tags/_menu_item.html.haml",
    "app/views/tags/_submenu_for_page.html.haml",
    "app/views/tags/_submenu_for_person.html.haml",
    "app/views/tags/_tag_list.html.haml",
    "app/views/tags/index.html.haml",
    "app/views/tags/show.html.haml",
    "app/views/users/_menu_item.html.haml",
    "app/views/users/confirmations/new.html.haml",
    "app/views/users/mailer/confirmation_instructions.html.haml",
    "app/views/users/mailer/reset_password_instructions.html.haml",
    "app/views/users/mailer/unlock_instructions.html.haml",
    "app/views/users/passwords/edit.html.haml",
    "app/views/users/passwords/new.html.haml",
    "app/views/users/registrations/edit.html.haml",
    "app/views/users/registrations/new.html.haml",
    "app/views/users/sessions/new.html.haml",
    "app/views/users/shared/_links.haml",
    "app/views/users/unlocks/new.html.haml",
    "config/initializers/devise.rb",
    "config/initializers/time_formats.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "cooperative.gemspec",
    "lib/cooperative.rb",
    "lib/cooperative/configuration.rb",
    "lib/cooperative/engine.rb",
    "lib/cooperative/localization.rb",
    "lib/cooperative/railtie.rb",
    "lib/cooperative/version.rb",
    "lib/generators/cooperative/install/install_generator.rb",
    "lib/generators/cooperative/install/templates/initializer.rb",
    "lib/generators/cooperative/install/templates/migrate/create_comments_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_groups_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_messages_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_pages_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_roles_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_statuses_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_users_roles_table.rb",
    "lib/generators/cooperative/install/templates/migrate/create_users_table.rb",
    "lib/generators/cooperative/utils.rb",
    "script/rails",
    "spec/behaviors/comments_behaviors.rb",
    "spec/behaviors/cooperative_behaviors.rb",
    "spec/behaviors/groups_behaviors.rb",
    "spec/behaviors/rateable_behaviors.rb",
    "spec/behaviors/statuses_behaviors.rb",
    "spec/controllers/activities_spec.rb",
    "spec/controllers/comments_spec.rb",
    "spec/controllers/follows_spec.rb",
    "spec/controllers/groups_spec.rb",
    "spec/controllers/messages_spec.rb",
    "spec/controllers/pages_spec.rb",
    "spec/controllers/people_spec.rb",
    "spec/controllers/profile_spec.rb",
    "spec/controllers/ratings_spec.rb",
    "spec/controllers/statuses_spec.rb",
    "spec/controllers/tags_spec.rb",
    "spec/cooperative_spec.rb",
    "spec/dummy/.rspec",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.css.scss",
    "spec/dummy/bin/bundle",
    "spec/dummy/bin/rails",
    "spec/dummy/bin/rake",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/bootstrap_pager_config.rb",
    "spec/dummy/config/initializers/bootswitch.rb",
    "spec/dummy/config/initializers/cooperative.rb",
    "spec/dummy/config/initializers/devise.rb",
    "spec/dummy/config/initializers/filter_parameter_logging.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/rolify.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/devise.en.yml",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/development.sqlite3",
    "spec/dummy/db/migrate/.keep",
    "spec/dummy/db/migrate/20130927215127_create_comments_table.rb",
    "spec/dummy/db/migrate/20130927215128_create_groups_table.rb",
    "spec/dummy/db/migrate/20130927215129_create_messages_table.rb",
    "spec/dummy/db/migrate/20130927215130_create_pages_table.rb",
    "spec/dummy/db/migrate/20130927215131_create_roles_table.rb",
    "spec/dummy/db/migrate/20130927215133_create_statuses_table.rb",
    "spec/dummy/db/migrate/20130927215134_create_users_table.rb",
    "spec/dummy/db/migrate/20130927215135_acts_as_follower_migration.rb",
    "spec/dummy/db/migrate/20130927215136_create_activities.rb",
    "spec/dummy/db/migrate/20130927215139_acts_as_taggable_on_migration.rb",
    "spec/dummy/db/migrate/20130927215142_create_person_ratings.rb",
    "spec/dummy/db/migrate/20130927215146_create_permissions_table.rb",
    "spec/dummy/db/migrate/20130927215309_create_users_roles_table.rb",
    "spec/dummy/db/migrate/20130929005901_chalk_dust_create_tables.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/db/test.sqlite3",
    "spec/dummy/db/test2.sqlite3",
    "spec/dummy/db/test3.sqlite3",
    "spec/dummy/db/test4.sqlite3",
    "spec/dummy/db/test5.sqlite3",
    "spec/dummy/db/test6.sqlite3",
    "spec/dummy/db/test7.sqlite3",
    "spec/dummy/db/test8.sqlite3",
    "spec/dummy/lib/assets/.gitkeep",
    "spec/dummy/public/403.html",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/system/images/5/large/hqdefault.jpg",
    "spec/dummy/public/system/images/5/medium/hqdefault.jpg",
    "spec/dummy/public/system/images/5/original/hqdefault.jpg",
    "spec/dummy/public/system/images/5/thumb/hqdefault.jpg",
    "spec/dummy/public/system/statuses/images/000/000/004/large/hqdefault.jpg",
    "spec/dummy/public/system/statuses/images/000/000/004/medium/hqdefault.jpg",
    "spec/dummy/public/system/statuses/images/000/000/004/original/hqdefault.jpg",
    "spec/dummy/public/system/statuses/images/000/000/004/thumb/hqdefault.jpg",
    "spec/dummy/public/system/users/images/000/000/001/large/Screenshot_from_2013-09-20_11_39_30.png",
    "spec/dummy/public/system/users/images/000/000/001/medium/Screenshot_from_2013-09-20_11_39_30.png",
    "spec/dummy/public/system/users/images/000/000/001/original/Screenshot_from_2013-09-20_11_39_30.png",
    "spec/dummy/public/system/users/images/000/000/001/thumb/Screenshot_from_2013-09-20_11_39_30.png",
    "spec/factories/comments.rb",
    "spec/factories/groups.rb",
    "spec/factories/messages.rb",
    "spec/factories/pages.rb",
    "spec/factories/statuses.rb",
    "spec/factories/users.rb",
    "spec/features/activities_spec.rb",
    "spec/features/groups_spec.rb",
    "spec/models/comment_spec.rb",
    "spec/models/group_spec.rb",
    "spec/models/message_spec.rb",
    "spec/models/page_spec.rb",
    "spec/models/role_spec.rb",
    "spec/models/status_spec.rb",
    "spec/models/tag_spec.rb",
    "spec/models/user_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/activities_support.rb",
    "spec/support/comments_support.rb",
    "spec/support/follower_support.rb",
    "spec/support/groups_support.rb",
    "spec/support/messages_support.rb",
    "spec/support/pages_support.rb",
    "spec/support/statuses_support.rb",
    "spec/support/tags_support.rb",
    "spec/support/users_support.rb",
    "vendor/assets/javascripts/jquery.caretposition.js",
    "vendor/assets/javascripts/jquery.spin.js",
    "vendor/assets/javascripts/jquery.tokenizer.js",
    "vendor/assets/javascripts/spin.js",
    "vendor/assets/javascripts/spin.min.js",
    "vendor/assets/javascripts/tag-it.js",
    "vendor/assets/javascripts/tag-it.min.js",
    "vendor/assets/stylesheets/tag-it.css",
    "vendor/assets/stylesheets/tokenizer.css"
  ]
  s.homepage = "https://github.com/nerakdon/cooperative.git"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Cooperative Social Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<coveralls>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 4.1"])
      s.add_runtime_dependency(%q<rails-i18n>, [">= 0"])
      s.add_runtime_dependency(%q<haml-rails>, [">= 0"])
      s.add_runtime_dependency(%q<bootstrap_forms>, [">= 0"])
      s.add_runtime_dependency(%q<breadcrumbs_on_rails>, [">= 0"])
      s.add_runtime_dependency(%q<bootstrap_pager>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_runtime_dependency(%q<tinymce-rails>, [">= 0"])
      s.add_runtime_dependency(%q<cancan>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<rolify>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<friendly_id>, [">= 0"])
      s.add_runtime_dependency(%q<public_activity>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_follower>, [">= 0"])
      s.add_runtime_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_opengraph>, [">= 0"])
      s.add_runtime_dependency(%q<opengraph>, [">= 0"])
      s.add_runtime_dependency(%q<chalk_dust>, [">= 0"])
      s.add_runtime_dependency(%q<coletivo>, [">= 0"])
      s.add_runtime_dependency(%q<bootstrap_leather>, [">= 0"])
      s.add_runtime_dependency(%q<private_person>, [">= 0"])
      s.add_runtime_dependency(%q<bootswitch>, [">= 0"])
      s.add_runtime_dependency(%q<erb2haml>, [">= 0"])
      s.add_runtime_dependency(%q<cooperative>, [">= 0"])
      s.add_development_dependency(%q<parallel_tests>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 4.1"])
      s.add_dependency(%q<rails-i18n>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<bootstrap_forms>, [">= 0"])
      s.add_dependency(%q<breadcrumbs_on_rails>, [">= 0"])
      s.add_dependency(%q<bootstrap_pager>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
      s.add_dependency(%q<tinymce-rails>, [">= 0"])
      s.add_dependency(%q<cancan>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rolify>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<friendly_id>, [">= 0"])
      s.add_dependency(%q<public_activity>, [">= 0"])
      s.add_dependency(%q<acts_as_follower>, [">= 0"])
      s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
      s.add_dependency(%q<acts_as_opengraph>, [">= 0"])
      s.add_dependency(%q<opengraph>, [">= 0"])
      s.add_dependency(%q<chalk_dust>, [">= 0"])
      s.add_dependency(%q<coletivo>, [">= 0"])
      s.add_dependency(%q<bootstrap_leather>, [">= 0"])
      s.add_dependency(%q<private_person>, [">= 0"])
      s.add_dependency(%q<bootswitch>, [">= 0"])
      s.add_dependency(%q<erb2haml>, [">= 0"])
      s.add_dependency(%q<cooperative>, [">= 0"])
      s.add_dependency(%q<parallel_tests>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 4.1"])
    s.add_dependency(%q<rails-i18n>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<bootstrap_forms>, [">= 0"])
    s.add_dependency(%q<breadcrumbs_on_rails>, [">= 0"])
    s.add_dependency(%q<bootstrap_pager>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<jquery-ui-rails>, [">= 0"])
    s.add_dependency(%q<tinymce-rails>, [">= 0"])
    s.add_dependency(%q<cancan>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rolify>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<friendly_id>, [">= 0"])
    s.add_dependency(%q<public_activity>, [">= 0"])
    s.add_dependency(%q<acts_as_follower>, [">= 0"])
    s.add_dependency(%q<acts-as-taggable-on>, [">= 0"])
    s.add_dependency(%q<acts_as_opengraph>, [">= 0"])
    s.add_dependency(%q<opengraph>, [">= 0"])
    s.add_dependency(%q<chalk_dust>, [">= 0"])
    s.add_dependency(%q<coletivo>, [">= 0"])
    s.add_dependency(%q<bootstrap_leather>, [">= 0"])
    s.add_dependency(%q<private_person>, [">= 0"])
    s.add_dependency(%q<bootswitch>, [">= 0"])
    s.add_dependency(%q<erb2haml>, [">= 0"])
    s.add_dependency(%q<cooperative>, [">= 0"])
    s.add_dependency(%q<parallel_tests>, [">= 0"])
  end
end

